"""Create tables

Revision ID: 319334ed7161
Revises: 
Create Date: 2024-10-10 16:11:07.700145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319334ed7161'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthday_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_birthday_lists'))
    )
    op.create_table('holiday_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holiday_lists'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('birthday_things',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_birthday_things_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_birthday_things'))
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blanket', sa.String(), nullable=True),
    sa.Column('food', sa.String(), nullable=True),
    sa.Column('clothes', sa.String(), nullable=True),
    sa.Column('towels', sa.String(), nullable=True),
    sa.Column('glass_things', sa.String(), nullable=True),
    sa.Column('cutlery', sa.String(), nullable=True),
    sa.Column('drinks', sa.String(), nullable=True),
    sa.Column('phone_accessories', sa.String(), nullable=True),
    sa.Column('accessories', sa.String(), nullable=True),
    sa.Column('candles', sa.String(), nullable=True),
    sa.Column('stationary', sa.String(), nullable=True),
    sa.Column('cosmetics_fragrances', sa.String(), nullable=True),
    sa.Column('toiletries', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_colors_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors'))
    )
    op.create_table('dreams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('things', sa.String(), nullable=True),
    sa.Column('places', sa.String(), nullable=True),
    sa.Column('states_coutries', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dreams_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dreams'))
    )
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('birthday_list_id', sa.Integer(), nullable=True),
    sa.Column('holiday_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['birthday_list_id'], ['birthday_lists.id'], name=op.f('fk_wishlists_birthday_list_id_birthday_lists')),
    sa.ForeignKeyConstraint(['holiday_list_id'], ['holiday_lists.id'], name=op.f('fk_wishlists_holiday_list_id_holiday_lists')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wishlists_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlists'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlists')
    op.drop_table('dreams')
    op.drop_table('colors')
    op.drop_table('birthday_things')
    op.drop_table('users')
    op.drop_table('holiday_lists')
    op.drop_table('birthday_lists')
    # ### end Alembic commands ###
