"""Create tables

Revision ID: b32befdd40bc
Revises: 319334ed7161
Create Date: 2024-10-18 21:50:39.235970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32befdd40bc'
down_revision = '319334ed7161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watched', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('feeling', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_movies_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies'))
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic', sa.String(), nullable=True),
    sa.Column('people', sa.String(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('story', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_photos_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_table('tv_showCs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watching', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('feeling', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tv_showCs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tv_showCs'))
    )
    op.create_table('tv_showFavs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('feeling', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tv_showFavs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tv_showFavs'))
    )
    op.create_table('tv_showFs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watched', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('feeling', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tv_showFs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tv_showFs'))
    )
    op.drop_table('wishlists')
    op.drop_table('holiday_lists')
    op.drop_table('birthday_lists')
    with op.batch_alter_table('birthday_things', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('des', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))

    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('des', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))
        batch_op.drop_column('blanket')
        batch_op.drop_column('cosmetics_fragrances')
        batch_op.drop_column('drinks')
        batch_op.drop_column('stationary')
        batch_op.drop_column('food')
        batch_op.drop_column('accessories')
        batch_op.drop_column('towels')
        batch_op.drop_column('glass_things')
        batch_op.drop_column('cutlery')
        batch_op.drop_column('phone_accessories')
        batch_op.drop_column('candles')
        batch_op.drop_column('clothes')
        batch_op.drop_column('toiletries')

    with op.batch_alter_table('dreams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('des', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))
        batch_op.drop_column('places')
        batch_op.drop_column('things')
        batch_op.drop_column('states_coutries')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dreams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('states_coutries', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('things', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('places', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('link')
        batch_op.drop_column('price')
        batch_op.drop_column('des')
        batch_op.drop_column('pic')

    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toiletries', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('clothes', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('candles', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('phone_accessories', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('cutlery', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('glass_things', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('towels', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('accessories', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('food', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('stationary', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('drinks', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('cosmetics_fragrances', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('blanket', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('link')
        batch_op.drop_column('price')
        batch_op.drop_column('des')
        batch_op.drop_column('pic')

    with op.batch_alter_table('birthday_things', schema=None) as batch_op:
        batch_op.drop_column('link')
        batch_op.drop_column('price')
        batch_op.drop_column('des')
        batch_op.drop_column('pic')

    op.create_table('birthday_lists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_birthday_lists')
    )
    op.create_table('holiday_lists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_holiday_lists')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('birthday_list_id', sa.INTEGER(), nullable=True),
    sa.Column('holiday_list_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['birthday_list_id'], ['birthday_lists.id'], name='fk_wishlists_birthday_list_id_birthday_lists'),
    sa.ForeignKeyConstraint(['holiday_list_id'], ['holiday_lists.id'], name='fk_wishlists_holiday_list_id_holiday_lists'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_wishlists_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_wishlists')
    )
    op.drop_table('tv_showFs')
    op.drop_table('tv_showFavs')
    op.drop_table('tv_showCs')
    op.drop_table('photos')
    op.drop_table('movies')
    # ### end Alembic commands ###
